### ISSUE TITLE
Protobuf: Type not supported

### ISSUE THREAD

**Issue by JarrodJ83** [fsharplang-ru/pulsar-client-dotnet#102]
I am trying to use Protobuf schema but running into the following exception when calling `client.NewProducer(Schema.PROTOBUF<MyMessage>()).Topic(topic)`. In this case `MyMessage` is generated by `Google.Protobuf`. :

`public sealed partial class MyMessage : pb::IMessage<RotationScheduled> { ... }`

>Type not supported","Source":"AvroSchemaGenerator","StackTraceString":"   at AvroSchemaGenerator.GenerateSchema.ToAvroDataType(String type)\n   at AvroSchemaGenerator.GenerateSchema.GetField(PropertyInfo p)\n   at AvroSchemaGenerator.GenerateSchema.GetUserDefinedProperties(PropertyInfo property, Dictionary`2 finalSchema)\n   at AvroSchemaGenerator.GenerateSchema.PropertyInfo(PropertyInfo property, Dictionary`2 finalSchema)\n   at AvroSchemaGenerator.GenerateSchema.GetSchema(Type type)\n   at Pulsar.Client.Schema.ProtobufSchema`1..ctor()\n   at Pulsar.Client.Api.Schema.PROTOBUF[T]()

I did not see any examples or documentation using protobuf so I am not sure if I am doing something incorrectly or if this is a bug. Could someone point me in the right direction? Thank you!

**Comment by Lanayx** [comment]
@JarrodJ83 You should **protobuf-net** instead. Pulsar doesn't support Protobuf schema actually, it still uses AVRO underneath, protobuf is used for serialization/deserialization only, so you should create POCO objects decorated with attributes to transfer data (schema is generated by looking at those POCO objects through reflection by [another library](https://github.com/eaba/AvroSchemaGenerator)). Here is [an example with protobuf](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/tests/IntegrationTests/Schema.fs#L181-L210)

**Comment by JarrodJ83** [comment]
Thanks @Lanayx I will give this a shot!

**Comment by Lanayx** [comment]
@JarrodJ83 were you able to accomplish your task?

**Comment by JarrodJ83** [comment]
@Lanayx I will try to get back to it this week. You can close this if you'd like. I am sure it will work once I get back to it. Thanks for circling back on it.
