### ISSUE TITLE
Create logo for the project

### ISSUE THREAD

**Issue by Lanayx** [fsharplang-ru/pulsar-client-dotnet#106]

**Comment by Lanayx** [comment]
Suggesting [purple circle background](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ee/.NET_Core_Logo.svg/600px-.NET_Core_Logo.svg.png) + [pulsar logo](https://pbs.twimg.com/profile_images/875130220474359809/wFcLUbwd_400x400.jpg) on the top (white lines)

**Comment by franck-schmidlin** [comment]
yep, 2 tone circle with white pulsar would work - let me see if I can throw something together

**Comment by franck-schmidlin** [comment]
![pulsar-client](https://user-images.githubusercontent.com/46777237/84647880-f776be00-aefb-11ea-901a-747b06798606.png)
something like that?

**Comment by Lanayx** [comment]
Right! If you can make a version with smooth lines, we'll use it :) [This svg](https://pulsar.apache.org/img/pulsar.svg) can help

**Comment by Lanayx** [comment]
I was able to make it :) Thank you @franck-schmidlin 
![pulsar-circle](https://user-images.githubusercontent.com/3329606/84657456-face7180-af1c-11ea-9728-6a019a5e9bcd.jpg)
