### ISSUE TITLE
Avro support should be able to use Avro generated C# classes

### ISSUE THREAD

**Issue by richardwilko** [fsharplang-ru/pulsar-client-dotnet#108]
If we use the C# classes Avro can generate (based on a Avro schema file), the avro schema support should be able to use it directly rather than trying to re-introspect the schema from the class file.

e.g. if i did this:
`
            var avroSchema = Avro.Schema.Parse(schemaJson);
            var codeGen = new CodeGen();
            codeGen.AddSchema(avroSchema);
            codeGen.GenerateCode();
            codeGen.WriteTypes(<my dir>);
`

I would get some C# classes implementing ISpecificRecord with a static Avro schema field _SCHEMA.

The java client looks for the equivalent field on the java class before falling back to the generic introspection approach.  Not sure if that would be possible here also?

**Comment by Lanayx** [comment]
@richardwilko can you please give an example of autogenerated C# class together with schema it was generated from?

**Comment by richardwilko** [comment]
@Lanayx Sure, here is a reasonably complex example: https://gist.github.com/richardwilko/5e0cc005db75cee448a4d2297c82dcba

**Comment by Lanayx** [comment]
Ok, it looks like it is possible to detect if class is implementing **ISpecificRecord** interface and if it does, then take schema information from **Schema** property. @richardwilko do you want to help with the implementation?

**Comment by richardwilko** [comment]
Happy to help, though as of this morning, I've written about 20 lines of c# and 0 lines of f#, so i need to do some reading.

I'm quite familiar with the JVM/Avro side of things though.

**Comment by Lanayx** [comment]
@richardwilko Ok, in that case you can handle just tests - can you please add a C# library into tests folder called **AvroGenerated** , put your generated classes in there, reference this library from unit tests project and add [a unit test](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/tests/UnitTests/Internal/SchemaTests.fs#L174) that will encode/decode using those classes. Once you have a failing test I'll add the code to fix it

**Comment by Lanayx** [comment]
Closed by #109
