### ISSUE TITLE
Add OAuth2 protocol support

### ISSUE THREAD

**Issue by Lanayx** [fsharplang-ru/pulsar-client-dotnet#119]
[Source code](https://github.com/apache/pulsar/tree/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/oauth2)
[Documentation](https://pulsar.apache.org/docs/en/security-oauth2/)

**Comment by fjod** [comment]
To write&debug this we will need some oauth2 server; I found [this](https://www.ory.sh/run-oauth2-server-open-source-api-security/) which I can run in Docker. Should I try to find another solution that can be used not only by me (free & running oauth2 server somewhere)?

upd: looks like I can use aws cognito with it's free tier for this purpose

**Comment by fjod** [comment]
Also this part is very unclear to me "You can use OAuth 2.0 access tokens to identify a Pulsar client and associate the Pulsar client with some "principal" (or "role"), which is permitted to do some actions, such as publishing messages to a topic or consume messages from a topic." Who can use tokens? Where to define these roles? I found [something](https://dev.to/greenroommate/apache-pulsar-oauth2-dev-setup-with-docker-and-keycloak-k64)  but hope for some guidance in pulsar server setting.

**Comment by Lanayx** [comment]
> 
> 
> To write&debug this we will need some oauth2 server; I found [this](https://www.ory.sh/run-oauth2-server-open-source-api-security/) which I can run in Docker. Should I try to find another solution that can be used not only by me (free & running oauth2 server somewhere)?
> 
> upd: looks like I can use aws cognito with it's free tier for this purpose

You are free to use any oauth2 server for writing/debugging purpose, we won't write integration tests for that. I can recommend using Google as such server, it should be easier than Cognito.

**Comment by Lanayx** [comment]
> 
> 
> Also this part is very unclear to me "You can use OAuth 2.0 access tokens to identify a Pulsar client and associate the Pulsar client with some "principal" (or "role"), which is permitted to do some actions, such as publishing messages to a topic or consume messages from a topic." Who can use tokens? Where to define these roles? I found [something](https://dev.to/greenroommate/apache-pulsar-oauth2-dev-setup-with-docker-and-keycloak-k64) but hope for some guidance in pulsar server setting.

Tokens are given to the client by OAuth2 server. The role will be encoded into such token. Pulsar server will grant permissions based on this role. To associate permissions with the role use the following link https://pulsar.apache.org/docs/en/admin-api-permissions/

**Comment by fjod** [comment]
> > To write&debug this we will need some oauth2 server; I found [this](https://www.ory.sh/run-oauth2-server-open-source-api-security/) which I can run in Docker. Should I try to find another solution that can be used not only by me (free & running oauth2 server somewhere)?
> > upd: looks like I can use aws cognito with it's free tier for this purpose
> 
> You are free to use any oauth2 server for writing/debugging purpose, we won't write integration tests for that. I can recommend using Google as such server, it should be easier than Cognito.

Looks like they used https://auth0.com/ for writing & testing initial code, at least samples lead there. I will stick to it too, Google is complicated for me :/

**Comment by Lanayx** [comment]
Ok, no problem :)

**Comment by fjod** [comment]
How we should behave in case of unsuccsessful auth?
In java code it just throws custom [exception ](https://github.com/apache/pulsar/blob/6704f12104219611164aa2bb5bbdfc929613f1bf/pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/oauth2/protocol/TokenClient.java#L105)
In F# tls code it also throws using [failwith ](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/6197029799c7e577bacf6a79d37e25b220d1d752/src/Pulsar.Client/Auth/AuthenticationDataTls.fs#L16)
I thought about injecting an Ilogger, but there is a chain of calls, starting from AuthenticationFactory to DefaultImplementation. So user has to provide ILogger instance? Or we can just failwith with error message ?

**Comment by Lanayx** [comment]
We should throw TokenExchangeException as well, you can add it to the [list of known exceptions](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Api/PulsarClientException.fs):
