### ISSUE TITLE
Broker Failure Causes SendAsync to Hang Indefinitely

### ISSUE THREAD

**Issue by JarrodJ83** [fsharplang-ru/pulsar-client-dotnet#121]
Today we were testing failure scenarios and ran into a situation where when we killed one of the brokers in our cluster the following code would just hang indefinitely on `producer.SendAsync`. Our cluster is hosted on k8s behind a proxy and it contains three brokers. If you see anything I am doing wrong that would cause this behavior please let me know. Thanks in advance!

**Steps to reproduce (in our case):**

1. Have a cluster with multiple brokers
2. Create a partitioned topic with at least as many partitions as brokers
3. Start below code to produce messages to topic
4. Kill one of the brokers

**Expected behavior:**

Either a) the producer handled trying to resend the message to a different broker until the SendTimeout elapsed at which an exception would be throw or b) the producer simply threw an exception when the SendTimeout elapsed and the client code would need to handle retry (like below) which should succeed since other brokers were available.

**Actual Behavior:**
Code never reached the catch and producer never sent another message even after broker was restored.

```
 static async Task Produce(PulsarClient pulsarClient, Topic topic, CancellationToken cancel)
        {
            Console.WriteLine($"Creating producer for {topic}");

            var producer = await pulsarClient.NewProducer()
                .ProducerName($"producer-{topic}")
                .SendTimeout(TimeSpan.FromSeconds(30))
                .Topic(topic.TopicName).CreateAsync();

            Console.WriteLine($"Producing to {topic}");

            while (!cancel.IsCancellationRequested)
            {
                try
                {
                    MessageId messageId =
                        await producer.SendAsync(System.Text.Encoding.UTF8.GetBytes(Guid.NewGuid().ToString()));

                    Console.WriteLine($"Produced MessageId {messageId} to {topic}");

                    await Task.Delay(1000);
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"Failed Publish: {ex}");
                    await Task.Delay(TimeSpan.FromSeconds(5));
                }
            }
        }
```

**Comment by Lanayx** [comment]
Hi! Can you please provide the client log as well? (That should be set up like [here](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/examples/FsharpExamples/Program.fs#L20))

**Comment by JarrodJ83** [comment]
Wow that produced a massive amount of logs! When the broker goes down it rapidly produces this set of logs over and over:

```
dbug: PulsarTester.Program[0]
      producer(3, producer-public/default/topic-1, 1) sendMessage id=17
dbug: PulsarTester.Program[0]
      Sending message of type Send
dbug: PulsarTester.Program[0]
      clientCnx(2, LogicalAddress
  Unspecified/pulsar-broker-2.pulsar-broker.pulsar.svc.cluster.local:6651) Got message of type SendReceipt
```

I've had a couple different results. One time it did throw the exception but then when it tried to send again it just spit out these logs indefinitely even after the one broker had come back online. The other time it never threw the exception even once and just got stuck in this state.

**Comment by Lanayx** [comment]
Thank you, I'll try to reproduce tomorrow. Those three log lines look perfectly fine for me - sending and receiving receipt

**Comment by JarrodJ83** [comment]
Thanks, @Lanayx! Let me know if there is anything else I can provide to assist.

**Comment by Lanayx** [comment]
@JarrodJ83 I've uploaded the new version, you are welcome to test

**Comment by JarrodJ83** [comment]
Thanks for the quick fix, @Lanayx ! Works like a charm now!
