### ISSUE TITLE
Allow Max Message Size to be configurable

### ISSUE THREAD

**Issue by Svade905** [fsharplang-ru/pulsar-client-dotnet#122]
Hi,

I see that in Commands.fs, the max message size is set to the default value that the broker also uses.

`let DEFAULT_MAX_MESSAGE_SIZE = 5_242_880 //5 * 1024 * 1024`

I have changed the configuration on the broker side so that the default message size is higher, however this client is preventing me from sending larger messages and throwing InvalidMessageException with the detail 'Message size is bigger than 5242880 bytes'.

Unless I missed something, I do not see an option to set the default message size so it would be a great help if it could be configured.

Thanks!

**Comment by Lanayx** [comment]
@Svade905 Hi! That's true that there is no client setting for that, since this value is coming from broker. Have you tried restarting broker after changing config? Also can you inspect client logs, max message size is clearly visible there when connection is established (you need one with brokerless=false).

**Comment by Svade905** [comment]
@Lanayx Ah so the value comes from the broker... ok. I **have** restarted the broker after changing config. I see in the broker logs that the max message size is set so I'm not sure what's going on.

I'm using the client in C#... is it possible and how do I see the client's logs? Also not sure what you meany by brokerless=false

**Comment by Lanayx** [comment]
You can check example project to see how the logger is set. (it is console logger there, but can be set to serilog or anything else)

**Comment by Svade905** [comment]
@Lanayx I managed to get a logger attached and I see the `maxMessageSize` is indeed **not** what I set in the broker config. I do have `brokerless: True` though which I'm not exactly sure the meaning of or how to change it.

Any idea whether the broker running in standalone mode prevents the use of the `maxMessageSize` setting? It's not available in the standalone config so I manually added it along with `nettyMaxFrameBytes` and the broker logs say it was set. Wondering whether it was actually set though.

**Comment by Lanayx** [comment]
@Svade905 Here is the log that I get when running example 

```
info: PulsarLogger[0]
      Connecting to { LogicalAddress = LogicalAddress Unspecified/my-pulsar-cluster:30002
  PhysicalAddress = PhysicalAddress Unspecified/my-pulsar-cluster:30002 } with maxMessageSize: 5242880, brokerless: True
info: PulsarLogger[0]
      Connected to { LogicalAddress = LogicalAddress Unspecified/my-pulsar-cluster:30002
  PhysicalAddress = PhysicalAddress Unspecified/my-pulsar-cluster:30002 }
info: PulsarLogger[0]
      clientCnx(1, LogicalAddress Unspecified/my-pulsar-cluster:30002) Connected ProtocolVersion: 15 ServerVersion: Pulsar Server MaxMessageSize: 0 Brokerless: True
info: PulsarLogger[0]
      Connecting to { LogicalAddress =
                  LogicalAddress
                    Unspecified/pu-pulsar-broker-1.pu-pulsar-broker.pulsar.svc.cluster.local:6650
  PhysicalAddress = PhysicalAddress Unspecified/my-pulsar-cluster:30002 } with maxMessageSize: 5242880, brokerless: False
info: PulsarLogger[0]
      Connected to { LogicalAddress =
                  LogicalAddress
                    Unspecified/pu-pulsar-broker-1.pu-pulsar-broker.pulsar.svc.cluster.local:6650
  PhysicalAddress = PhysicalAddress Unspecified/my-pulsar-cluster:30002 }
info: PulsarLogger[0]
      clientCnx(2, LogicalAddress
  Unspecified/pu-pulsar-broker-1.pu-pulsar-broker.pulsar.svc.cluster.local:6650) Connected ProtocolVersion: 15 ServerVersion: Pulsar Server MaxMessageSize: 5242880 Brokerless: False

```
The second connected log is what you need to look at

**Comment by Lanayx** [comment]
Ah, it's probably because I'm using proxy :) Anyway, the MaxMessageSize from this log is what is returned back from the cluster. [The code](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Internal/ClientCnx.fs#L396)

**Comment by Svade905** [comment]
Yeah I don't see the false so must be the proxy.

Here's my logs, I notice that the maxMessageSize values are different in the 1st and 3rd log message.

```
info: PulsarLogger[0]
    Connecting to { LogicalAddress = LogicalAddress Unspecified/192.168.1.147:6650
  PhysicalAddress = PhysicalAddress Unspecified/192.168.1.147:6650 } with maxMessageSize: 5242880, brokerless: True
info: PulsarLogger[0]
    Connected to { LogicalAddress = LogicalAddress Unspecified/192.168.1.147:6650
  PhysicalAddress = PhysicalAddress Unspecified/192.168.1.147:6650 }
info: PulsarLogger[0]
    clientCnx(1, LogicalAddress Unspecified/192.168.1.147:6650) Connected ProtocolVersion: 15 ServerVersion: Pulsar Server MaxMessageSize: 52528800 Brokerless: True
```

**Comment by Lanayx** [comment]
So it seems to be 52528800 - around 50Mb for you, does the error still display `Message size is bigger than 5242880 bytes` ? Can you show other logs till the exception?

**Comment by Svade905** [comment]
Yes that's correct, around 50Mb.

I'm attempting to send a message which has a size of about 11Mb and the error I get is:

`InvalidMessageException: Message size is bigger than 5242880 bytes`

So that's the default max message size.

Other logs continuing from previously after creating producer, nothing of value:

```
info: PulsarLogger[0]
    producer(1, name, -1) starting register to topic persistent://test/test2/test3
info: PulsarLogger[0]
    producer(1, name, -1) registered with name name
dbug: PulsarLogger[0]
    producer(1, name, -1) BeginSendMessage
```
Exception is thrown after that last log and no more log messages.

Batching is disabled

**Comment by Lanayx** [comment]
I see, the correct behavior will be to reconnect with new maxMessageSize, it is tested in "Send large message works fine" integration test which gets passed successfully in github actions. I'll try to reproduce locally, in a while can you please make sure that you are running the latest library version

**Comment by Svade905** [comment]
I reproduced the same issue with the latest libraries and installations so Pulsar.Client 1.6.1 and Apache Pulsar 2.6.1. Running the broker in standalone mode.

I put these settings into standalone.conf:

```
maxMessageSize=52428800
nettyMaxFrameBytes=52428800
```

My C# .Net framework console project code to test it quickly:

```
        static async Task Main(string[] args)
        {
            var loggerFactory = LoggerFactory.Create(builder =>
            builder
            .SetMinimumLevel(LogLevel.Debug)
            .AddConsole()
            );

            PulsarClient.Logger = loggerFactory.CreateLogger("PulsarLogger");

            var client = new PulsarClientBuilder()
                .ServiceUrl(url)
                .Build();

            var producer = await client.NewProducer()
                .Topic("max-size-topic")
                .ProducerName(Guid.NewGuid().ToString())
                .EnableBatching(false)
                .CreateAsync();

            var dummyText = new string('@', 10000000);
            //System.IO.File.WriteAllText(@"C:\Temp\dummy.txt", dummyText);

            await producer.SendAsync(Encoding.UTF8.GetBytes(dummyText));

            var consumer = await client.NewConsumer()
                .Topic("max-size-topic")
                .ConsumerName(Guid.NewGuid().ToString())
                .SubscriptionInitialPosition(Pulsar.Client.Common.SubscriptionInitialPosition.Earliest)
                .SubscriptionType(Pulsar.Client.Common.SubscriptionType.Shared)
                .SubscriptionName(Guid.NewGuid().ToString())
                .SubscribeAsync();

            var msg = await consumer.ReceiveAsync();
            await consumer.AcknowledgeAsync(msg.MessageId);

            Console.WriteLine("Message received: " + Encoding.UTF8.GetString(msg.Data));

            await producer.DisposeAsync();
            await consumer.DisposeAsync();
            await client.CloseAsync();
        }
```

**Comment by Lanayx** [comment]
@Svade905 Thank you! I've found the issue, it was indeed due to the "brokerless" logic, I'll release the update soon.

**Comment by Svade905** [comment]
@Lanayx Thanks. I've tested it and it does not throw the exception anymore!

Unfortunately I'm getting a timeout exception now and I think it's something on the broker side since I see `NotEnoughBookiesException: Not enough non-faulty bookies available`

and

`ERROR org.apache.bookkeeper.proto.BookieRequestHandler - Unhandled exception occurred in I/O thread or handler
io.netty.handler.codec.TooLongFrameException: Adjusted frame length exceeds 5242880: 10000132 - discarded`

Setting the max message size setting does not seem as straight forward. Seems like I can't set bookkeeper settings from standalone. Any chance you would know a bit more about this? Googling around and there doesn't seem to be any answers.

**Comment by Lanayx** [comment]
@Svade905 Right, you need to set this to bookeeper config `nettyMaxFrameBytes=52428800`

**Comment by Svade905** [comment]
Didn't work. I think I will have to stop using standalone.

I was attempting stuff from this issue https://github.com/apache/pulsar/issues/4708 but didn't seem to help.

**Comment by Lanayx** [comment]
@Svade905 I've just noticed that the setting name is misspelled, can you try `nettyMaxFrameSizeBytes`  ?

**Comment by Svade905** [comment]
@Lanayx Awesome, it works now! Thanks a lot. Happy to close the issue if you are.
