### ISSUE TITLE
Request: Make Consumer/Producer Builder Properties Publicly Available

### ISSUE THREAD

**Issue by JarrodJ83** [fsharplang-ru/pulsar-client-dotnet#123]
I have a use case where I am manually creating my topics instead of letting them be automatically generated on the creation of the producer/consumer. I also need to create dead letter topics for the consumers. That said this becomes tricky because the code that is going to create the topics needs passed all the information about the topic and whether or not the consumer is setup for dead letter, what the dead letter topic name is, etc. The consumer/producer builders contain all of this information. What would be ideal is if I could just pass the builders to this code and glean the configuration from them. I am sure you are trying to keep them idempotent so my request would be to have additional Get methods for each of the properties so that these can be the "source of truth" for other code that needs to know about the topics and their producers/consumers. I am not familiar with fsharp but if this sounds interesting and you do not have enough time to tackle I would be glad to take a crack at it.

**Comment by Lanayx** [comment]
@JarrodJ83 Hi! It seems that this is already supported :) For example: 

```
var genericConsumerBuilder = client.NewConsumer()
                .Topic("MyTopic")
                .SubscriptionName("abc");
```

```
var consumer1 = await genericConsumerBuilder.Topic("MyTopic1").SubscribeAsync();
var consumer2 = await genericConsumerBuilder.Topic("MyTopic2").SubscribeAsync();
```

**Comment by JarrodJ83** [comment]
Hi @Lanayx I should have provided some code example. What I am looking for is to be able to access the properties of the builder. For example, building on your code above:

```
async Task CreateConsumerTopics(IConsumerBuilder<T> consumerBuilder) 
{
     var topic = consumerBuilder.Topic; // or something like consumerBuilder.GetTopic()  ?
     var deadLetterTopic = consumerBuilder.DeadLettersPolicy?.DeadLetterTopic;;

     // call admin api to create topic and it's dead letter topic
}

await CreateDeadLetterForConsumer(genericConsumerBuilder);
```

Currently all properties of the builders are private. I would like them to either be public with private setters or have methods to get them. Does this make sense?

**Comment by Lanayx** [comment]
Thank you, now I understand it better :) You are right, It's useful to add. For example dead letter policy will be accessible through
`consumerBuilder.Configuration.DeadLetterPolicy`
