### ISSUE TITLE
Compression?

### ISSUE THREAD

**Issue by MikeDotNetty** [fsharplang-ru/pulsar-client-dotnet#125]
Sorry if this is obvious, but when the pulsar client is attempting to decompress a message what compressionType is used?  Also as a consumer can I specify an individual compressionType in any way (assuming I know how the message was initially compressed)?  I am running into the following error upon receiving a message:

```
info: PulsarLogger[0]
      consumer(1, , -1) Message 5*****9:41088:-1 was discarded due to DecompressionError
fail: PulsarLogger[0]
      consumer(1, , -1) Decompression exception 5175679:41089:-1
ComponentAce.Compression.Libs.zlib.ZStreamException: inflating:
   at ComponentAce.Compression.Libs.zlib.ZOutputStream.finish()
   at Pulsar.Client.Internal.CompressionCodec.ZLibCompression.zlib(Boolean isEncode, Int32 capacity, Byte[] bytes, Int32 payloadLength) in D:\Work\Pulsar.Client\src\Pulsar.Client\Internal\Compression .fs:line 30
   at Pulsar.Client.Internal.CompressionCodec.ZLibCompression.Pulsar-Client-Internal-ICompressionCodec-Decode(Int32 uncompressedSize, Byte[] src) in D:\Work\Pulsar.Client\src\Pulsar.Client\Internal\Compression .fs:line 35
   at Pulsar.Client.Api.ConsumerImpl`1.decompressMessage(RawMessage rawMessage, Boolean isChunked) in D:\Work\Pulsar.Client\src\Pulsar.Client\Internal\ConsumerImpl.fs:line 485
info: PulsarLogger[0]
      consumer(1, , -1) Message 5*****9:41089:-1 was discarded due to DecompressionError
```

Thanks!

**Comment by Lanayx** [comment]
Hi! The decompression is based on the metadata that is sent in the message, so you can't use custom decompression algorithm at the moment, was it your intention? [Code reference](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Internal/ConsumerImpl.fs#L484). Codecs logic is [here](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Internal/Compression%20.fs)

**Comment by MikeDotNetty** [comment]
@Lanayx Thanks for the response and information.  However, no I was not trying to use a custom algorithm, but rather I was wondering if I could tell the pulsar client which of the compressionTypes to use.   However, I was provided more information that this particular message is in fact compressed using ZLIB....and seeing as how the pulsar client is attempting to decompress using the ZlibCompression, I have to assume it's already using the ZLIB algorithm.   

The odd thing, is I was also informed that other people are able to consume this same topic's ZLIB compressed messages, the only difference being I am the only one using the pulsar-client-dotnet.   Don't get me wrong, I have been using this pulsar-client-dotnet for quite some time now with other topics and it's been working great.  Anyway, thoughts?

**Comment by Lanayx** [comment]
Here is [the code of decompression](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Internal/Compression%20.fs#L23-L31), it's very straightforward :) Do you see any issues there? Feel free to correct it, or to provide a console application with a more correct decompression. I'll try to do the testing on my side as well, within few days

**Comment by Lanayx** [comment]
@MikeDotNetty I've investigated the issue a bit and found that indeed **java -> .net** transformation doesn't work, while the other side **.net -> java** works fine. Looks like the reason is some non-standard way of encoding, for example the text _Hello from Java 1_ gets encoded to `eJzySM3JyVdIK8rPVfBKLEtUMAQAAAD//w==` in Java and to `eJzzSM3JyVdIK8rPVfBKLEtUMAQANpoFvA==` in .net version. [Online decoder](http://www.txtwizard.net/compression) (use deflate option) works well for .net version, but can't decode Java one. So it looks that some investigation is required to decode that non-standard Java output.

**Comment by MikeDotNetty** [comment]
@Lanayx Thanks for the quick investigation and reply back.  Also glad to see that I'm not nuts :)  This certainly does explain why there is an issue with the decompression.  I wish I could assist, but this is well beyond my scope.   If you wouldn't mind keeping me in the loop as to your further findings that would be appreciated!  Thanks again!

**Comment by Lanayx** [comment]
@MikeDotNetty After several hours of dancing around the zlib library I've managed to find the similar setup to Java, so closing the ticket. 1.7.2 is released with the fix

**Comment by MikeDotNetty** [comment]
@Lanayx Sorry for the delayed response.  HOWEVER, you bug fix did the trick!  Much appreciated!
