### ISSUE TITLE
Expose state of Client

### ISSUE THREAD

**Issue by Sacagawea69** [fsharplang-ru/pulsar-client-dotnet#131]
Hi,

I'm using C# and would like to check whether or not my client has successfully connected after creation. Currently I am only able to see if there are any connection issues when attempting to send or receive messages.

For example

bool successful;

var client = new PulsarClientBuilder()
                .ServiceUrl(serviceUrl)
                .Build();

if (client.State() == Connected)
{ 
        successful = true;
}  

Thanks

**Comment by Lanayx** [comment]
Hi, @Sacagawea69! A connection attempt is not happening when client instance is created. If serviceUrl is misspelled then you'll get a connection error on consumer or producer creation, no need to receive or send messages.

**Comment by Sacagawea69** [comment]
Hi, 
Thanks for the reply. Do connection attempts only happen at the point of sending and receiving messages? I would like to know prior to this whether or not a connection is successful/possible

**Comment by Lanayx** [comment]
@Sacagawea69 As I said in my previous message: "If serviceUrl is misspelled then you'll get a connection error **on consumer or producer creation**, no need to receive or send messages."

**Comment by Sacagawea69** [comment]
@Lanayx my specific scenario is if the broker has been turned off (or not started) when creating the client, (meaning a connection is not possible at that point in time) there is currently no flag to make this known at the time of creating the client, which is what I'm trying to do. 

looking at the source code there is an internal field 'clientState' which  can be either Active, Closing, or Closed. what is this in relation to. what defines an active/closing/closed client?

**Comment by Lanayx** [comment]
@Sacagawea69 So you need to try create a consumer or a producer, if it fails then connection is not established. The state of client is always Active until it starts closing

**Comment by Lanayx** [comment]
@Sacagawea69, please check 2.0.0 updates. Client state is exposed, the build api has changed to buildAsync. In case transactions are enabled this will check connection to the broker.
