### ISSUE TITLE
Support for PROTOBUFNATIVE schema type (added pulsar 2.7)

### ISSUE THREAD

**Issue by richardwilko** [fsharplang-ru/pulsar-client-dotnet#132]
Any plans to add support for the PROTOBUFNATIVE schema type, which was added in pulsar 2.7.

https://github.com/apache/pulsar/pull/8372

**Comment by Lanayx** [comment]
@richardwilko Sure, everything from java client is on roadmap, do you want to contribute this feature?

**Comment by richardwilko** [comment]
@Lanayx I cant promise I will get a chance to look anytime before the new year unfortunately

**Comment by Lanayx** [comment]
It's ok, i'm going to finish porting 2.6.2 changes first anyway, then transactions support will be the highest priority

**Comment by Lanayx** [comment]
Closing as implemented by @fjod
