### ISSUE TITLE
Add CancellationToken to IReader.ReadNextAsync

### ISSUE THREAD

**Issue by TjeuKayim** [fsharplang-ru/pulsar-client-dotnet#135]
`ReceiveAsync` recently got an overload with a `CancellationToken` parameter in #115.
`IReader.ReadNextAsync` uses that method in its implementation, so it could easily get a similar overload.

My use case if that I want to specify a timeout when the reader has reached the latest message and waits for new ones to arrive.
This would be a workaround for my other issue #134.

**Comment by Lanayx** [comment]
Closed with 1.8.1 release
