### ISSUE TITLE
Feature request: Expose Message.PublishTime

### ISSUE THREAD

**Issue by TjeuKayim** [fsharplang-ru/pulsar-client-dotnet#138]
Other Pulsar client libraries expose something like [`Message.getPublishTime()`](https://github.com/apache/pulsar/blob/2fb8cfe13130b87cb011c1e37ac5b8dfd5605acb/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/Message.java#L90-L96) to read the publish time.

`RawMessage.Metadata` already stores the publish-time, it is just not exposed as part of the public API.

**Comment by Lanayx** [comment]
Available in 1.8.2
