### ISSUE TITLE
Lazy initialization of consumer

### ISSUE THREAD

**Issue by kuskmen** [fsharplang-ru/pulsar-client-dotnet#140]
Hello, 

This is most likely I mistake from my side, but I can't seem to find anything on the internet so I will try to take my chances here. Anyway, straight to the topic. I am writing an infrastructure nuget for our company in order to abstract PubSub pattern, ideally, our applications should install this nuget and register `IPubSub` in their application DI container and later work with it. I did this easily, but for stage 2, now I want both producer and consumer to be constructed lazily. So I created myself AsyncLazy type and started working with it. Everything seems to be working as expected from the construction point of view, both producer and consumer are initialized lazily and the time they are requested first but consumer seems to be blocked indefinitely waiting for msg (this is a guess I am verifying this using my unit tests)

So my question is, could it be since the consumer is lazily constructed *after* the producer, that the first msg by the producer is not sent by pulsar to the consumer, since at the point of publishing no active subscriptions for this topic were found? If so, do you have some advice how can I handle this because I really want my PubSub using lazy construction.

**Comment by Lanayx** [comment]
@kuskmen Hi, this is indeed the case, if you start producing without any active consumers then the message is gone (but only the first time, once subscription is created the order doesn't matter). A workaround is to set retention to the topic: [example](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/tests/IntegrationTests/commands.txt#L3)

**Comment by kuskmen** [comment]
Hi, thank you very much for the fast reply, I will read about retention and decide if this is suitable for us.
