### ISSUE TITLE
MessageID equality problem

### ISSUE THREAD

**Issue by sijie** [fsharplang-ru/pulsar-client-dotnet#146]
*Problem*

The MessageID returned by a Producer doesn't match the MessageID returned by a Consumer.

The problem is due to the way of comparing MessageID.Type. When comparing MessageID.Type, there should be no need to compare BatchMessageAcker. The MessageID.Type.BatchMessageAcker returned from the producer is `null`, but that returned from the consumer is not `null`. This leads to the difference in comparison when comparing the MessageID of one same message. When MessageID is serialized and then deserialized, MessageID.BatchMessageAcker is also set to `null` when calling `MessageID.FromByteArray`. 

A temporary solution is to disable batching. But a proper fix is to fix the `MessageID` equality method to exclude `BatchMessageAcker` in the comparison.

**Comment by Lanayx** [comment]
Thanks for reporting! Will fix it soon
