### ISSUE TITLE
Connection recovery of publisher and consumer?

### ISSUE THREAD

**Issue by kuskmen** [fsharplang-ru/pulsar-client-dotnet#151]
Hi guys, 

I am trying to write myself integration tests for our company wrapper NuGet regarding ack and nack functionality (basically I want to test that my wrapper doesn't do something wrong).

The test is doing the following things:

```
// subscribe
// start pushing msgs (0-10) <- in parallel
// start consuming <- await
// acknowledge msg(0) <- await

// restart docker pulsar service

// start consuming (expect to start from 1-10) <-- however this takes ages to "recover" I am not sure if it does have such configuration
```

The question is: Do I need to make recovery on my side or there is some configuration that I can tweak on your side so connections that are lost can be retried faster?

P.S. Also what I noticed is that sometimes my message that is consumed starts from 1 rather than 0, could this be caused due to some awkward ordering of pulsar message or message(0) is lost? 👻 

Thanks in advance!

**Comment by Lanayx** [comment]
Hello!
As for first message - it happens because acknowledge doesn't happen immediately, rather by timer, so sometimes ack reaches server before restart, sometimes it doesn't.
Can you please specify the "ages" time please? As well as the time for the pulsar service to become healthy?

**Comment by kuskmen** [comment]
I gave pulsar service 10-15 seconds after the restart, then initially (before I dropped the timeout) I gave a consumption timeout of 15 seconds before my test fails and again it was very indeterministic whether it will start consuming again for this period or not - sometimes it does sometimes it doesn't. Unfortunately, I cant provide you with deterministic example, but I think it shouldn't take more than 10 seconds for client to recover if docker + pulsar service are ready.

Also what I notice is that sometimes client completely "falls apart" by throwing `System.TimeoutException: Could not GetPartitionedTopicMetadata within the configured timeout`, _however_, I think this might be related to the pulsar service itself or the local standalone cluster that I am running since I notice it usually throws exceptions 

[PulsarError.txt](https://github.com/fsharplang-ru/pulsar-client-dotnet/files/6118535/PulsarError.txt) (search for "ERROR")

**Comment by Lanayx** [comment]
Thank you, I think the issue is that pulsar is down for too long, so retries can get up to 1 minute. You can tweak OperationTimeout setting on PulsarClient construction. You should also add logging (like in examples or integration tests in this repo), since the retries should be visible there at Warning level. Also, please check if you are using the latest library version.

**Comment by kuskmen** [comment]
Okay, good to know. I am using last version of the library what about the message being lost or not coming in order how can I trace that?

**Comment by Lanayx** [comment]
Yes, you can trace that, just enable logging in debug mode and check ack logs. I don't see the message lost or out of order in your example - it is either processed once or twice

**Comment by Lanayx** [comment]
Closing as inactive
