### ISSUE TITLE
The code of Exception handling exceptions differently between Producer and Consumer

### ISSUE THREAD

**Issue by jiazhai** [fsharplang-ru/pulsar-client-dotnet#152]
The producer reports exceptions differently than Consumer.  Consumer reports them through TaskCompletionSource (same as v.1.8.x), while Producer seems to throw them directly.

**Comment by Lanayx** [comment]
Hi, @jiazhai ! Can you please give examples with stacktraces?

**Comment by Lanayx** [comment]
Closing as abandoned
