### ISSUE TITLE
Consumer.Seek unexpected behavior when repeat seek

### ISSUE THREAD

**Issue by jiazhai** [fsharplang-ru/pulsar-client-dotnet#153]
Thanks to @Lanayx 's help on the former Consumer.Seek issue #147, but seems it was not fixed completely. 
Consider the integration test in the attachment. The first time you execute SeekAsync / ReceiveAsync operation sequence – it works. But if you repeat that sequence several times in a row, the test inevitably fails in one of two ways:

1.       Either it reports that Consumer is disconnected (there is no API to check if Consumer is connected).
2.       Consumer receives a wrong message after a seemingly successful Seek operation.

[RandomSeekTest.cs.txt](https://github.com/fsharplang-ru/pulsar-client-dotnet/files/6127545/RandomSeekTest.cs.txt)

FYI. @RobertIndie

**Comment by Lanayx** [comment]
Hi, @jiazhai! I've made a fix for the wrong message which will be released in 2.1.0. I couldn't reproduce the fail (your 1st point)

**Comment by jiazhai** [comment]
Thanks @Lanayx.

**Comment by RobertIndie** [comment]
Regard the first point. I found a problem with the test code.
During the random seek, the 99th message may be sought. At this time, the consumer will wait for the 100th message, but the producer no longer sends messages, which will cause the test to remain stuck in this place.

So I change the part `Act` of the code to like this:
```csharp
// Act 
var rnd = new Random(DateTime.Now.Millisecond);
var receivedMessages = new Dictionary<int, Message<byte[]>>(numberOfMessages);
for (int idx = 0; idx < numberOfRandomSeeks; idx++)
{
    var randomIdx = rnd.Next(0, numberOfMessages - 1); // add '-1' to avoid seek to the 99th messages
    if (!receivedMessages.ContainsKey(randomIdx))
    {
        await consumer.SeekAsync(producedMessageIds[randomIdx]);
        receivedMessages[randomIdx] = await consumer.ReceiveAsync();
    }
}
```
I don’t know if this is the cause of the problem.

**Comment by Lanayx** [comment]
@RobertIndie I didn't use your code, rather wrote my own test :) The problem is that fix for issue 147 wasn't good enough, rather than ignoring messages before startMessageId, it should ignore all the messages coming between seek request and reconnect, this was covered in the fix to the current issue.
