### ISSUE TITLE
Add OpenTelemetry support

### ISSUE THREAD

**Issue by Lanayx** [fsharplang-ru/pulsar-client-dotnet#155]
https://devblogs.microsoft.com/dotnet/opentelemetry-net-reaches-v1-0/#library-authors
Java implementations for reference https://github.com/riferrei/otel-with-apache-pulsar, https://github.com/streamnative/pulsar-tracing

**Comment by fjod** [comment]
So as far as I understood for now:

There are already interfaces for it:
https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/6197029799c7e577bacf6a79d37e25b220d1d752/src/Pulsar.Client/Api/IProducerInterceptor.fs

https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/6197029799c7e577bacf6a79d37e25b220d1d752/src/Pulsar.Client/Api/IConsumerInterceptor.fs

So we can create implementations for it like [this ](https://github.com/riferrei/otel-with-apache-pulsar/blob/main/brand-estimator/src/main/java/com/riferrei/otel/pulsar/OTelConsumerInterceptor.java)
which can trace pulsar work using .net open telemetry like [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/docs/trace/getting-started/README.md)

I dont understand how to let user know about it (Intellisense could help here) and how user can set trace output. I mean, in .net example there is console output, in first java impl there is Elastic impl (I failed to understand how it works). It should be configurable by user though - mb [exporter libs](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/glossary.md#exporter-library) are just for it? 

Also it would require adding some package for open-telemetry.

**Comment by Lanayx** [comment]
My understanding is that we create another nuget library `Pulsar.Client.Otel` where we place 2 implementations of the interfaces you mentioned above. We can keep it in this repository or create another repository with the source code and console examples. Users should be able to configure their own exporters, the injection api should be just like [in the example](https://github.com/riferrei/otel-with-apache-pulsar/blob/9802f2b198dd4419ca1429870feca5dcbbe80ba2/brand-estimator/src/main/java/com/riferrei/otel/pulsar/config/PulsarConfiguration.java#L41)

**Comment by fjod** [comment]
I think simple console output for test purposes should be enough? In example, big piece of work is about elastic/kibana/docker etc. I will spend more time wiring nice output than writing code

**Comment by Lanayx** [comment]
Yes, it will be enough

**Comment by fjod** [comment]
I got question about Propagation & Baggage API.  Propagatation is [here](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry.Api/README.md)  (scroll down) and [General info about Baggage](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/baggage/api.md). So there is an example with Rabbit MQ where it creates [props](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a25741030f05c60c85be102ce7c33f3899290d49/examples/MicroserviceExample/Utils/Messaging/MessageSender.cs#L60) which contains special properties for [RMQ ](https://github.com/open-telemetry/opentelemetry-dotnet/blob/a25741030f05c60c85be102ce7c33f3899290d49/examples/MicroserviceExample/Utils/Messaging/RabbitMqHelper.cs#L48)  Do we need similar functionality? What information should be passed from producer interceptor to consumer interceptor, if any?  Also it would need adding OpenTelemetry.Api nuget (now I only use System.Diagnostics.DiagnosticSource).

**Comment by Lanayx** [comment]
I think we do need Propagation functionality, since it [was implemented in Java](https://github.com/riferrei/otel-with-apache-pulsar/blob/main/brand-estimator/src/main/java/com/riferrei/otel/pulsar/OTelProducerInterceptor.java#L75-L76). As for Baggage API, I don't think we should use it, it's not planned https://github.com/streamnative/pulsar-tracing/issues/12
