### ISSUE TITLE
Support for Transactions in Pulsar 2.8.0

### ISSUE THREAD

**Issue by danielcrabtree** [fsharplang-ru/pulsar-client-dotnet#167]
I'm wondering if the client supports Pulsar 2.8.0 yet?

I am trying to use Transactions and the C# Transactions example does not run. It fails with the following exception:
```Unhandled exception. System.AggregateException: One or more errors occurred. (org.apache.pulsar.transaction.coordinator.exceptions.CoordinatorException$TransactionNotFoundException: The transaction with this txdID `(1,4)`not found )```

Note: I have found that it is required to add ProducerName and ConsumerName, otherwise it will not get this far. With other examples, e.g. the Simple producer/consumer example, this is sufficient to make them work with Pulsar 2.8.0.

If I rearrange the example Transaction code to make use of the transaction sooner, I get a similar, but slightly more informative exception:
```Unhandled exception. System.AggregateException: One or more errors occurred. (org.apache.pulsar.transaction.coordinator.exceptions.CoordinatorException$InvalidTxnStatusException: Expect Txn `(1,2)` to be in OPEN status but it is in ABORTED status)```

Some additional details:
I am running a clean copy of the Standalone version of Pulsar 2.8.0 with no configuration changes except to enable Transaction support on CentOS 7:
transactionCoordinatorEnabled=true
bin/pulsar initialize-transaction-coordinator-metadata -cs 127.0.0.1:2181 -c standalone

**Comment by Lanayx** [comment]
Hi, @danielcrabtree ! Thanks for asking, transactions functionality was tested with Pulsar 2.7.*, it seems that the transactions support on server has changed significantly in 2.8.0, so client update is required. I'll start working on the update this week.

**Comment by danielcrabtree** [comment]
That's great! Thanks @Lanayx 

I'll be happy to help test the update once it's ready.

**Comment by Lanayx** [comment]
@danielcrabtree Hi, I've just released 2.5.0, you are welcome to try. Client 2.5.0 will be incompatible with broker 2.7.* transactions

**Comment by danielcrabtree** [comment]
@Lanayx Thanks for getting this updated. I've done some initial tests with 2.5.0 and everything seems to be working well so far.

**Comment by Lanayx** [comment]
There is one additional fix in 2.5.2, now all transaction tests are passing, closing the ticket
