### ISSUE TITLE
Change all mailboxes to channels to improve performance

### ISSUE THREAD

**Issue by Lanayx** [fsharplang-ru/pulsar-client-dotnet#168]
[Benchmark results](https://github.com/Lanayx/hlc2/blob/master/src/Benchmarks/AsyncReply.fs)

**Comment by TiraelSedai** [comment]
I'm working on it, albeit a bit slow.

**Comment by Lanayx** [comment]
@TiraelSedai You can use those 2 helpers to simplify changes
```fsharp
let postAndAsyncReply (channel: Channel<'T>) f =
    let tcs = TaskCompletionSource(TaskContinuationOptions.RunContinuationsAsynchronously)
    (f tcs) |> channel.Writer.TryWrite |> ignore
    tcs.Task
    
let post (channel: Channel<'T>) =
    channel.Writer.TryWrite >> ignore
```

Usage:
Old : `(fun epoch -> this.Mb.Post(ProducerMessage.ConnectionOpened epoch))`
New: `(fun epoch -> post this.Mb(ProducerMessage.ConnectionOpened epoch))`
