### ISSUE TITLE
Can this C# client run under .NET-Standard or .NET-Framework (instead of .NET-Core)?

### ISSUE THREAD

**Issue by mike3041** [fsharplang-ru/pulsar-client-dotnet#184]
My environment doesn't allow .NET-Core. It only allows .NET-Framework 4.7

**Comment by Lanayx** [comment]
Hi! This is not C# client, this is .NET client, which is packaged as .NET Standard 2.0, you can see it on nuget page

**Comment by Lanayx** [comment]
Example project with old dotnet [is here](https://github.com/fsharplang-ru/pulsar-client-dotnet/tree/develop/examples/OldDotnetExample)
