### ISSUE TITLE
Release for enum schema type supprot

### ISSUE THREAD

**Issue by RobertIndie** [fsharplang-ru/pulsar-client-dotnet#188]
Since https://github.com/eaba/AvroSchemaGenerator/pull/19 has been merged and AvroSchemaGenerator 2.2.0 has been released. Could we cut a new release for this client? @Lanayx

**Comment by Lanayx** [comment]
Hi, @RobertIndie ! There is no need to cut another release, dependency can be updated separately.

**Comment by RobertIndie** [comment]
Get it. Thanks!
