### ISSUE TITLE
Make acknowledgments to be sent on consumer close

### ISSUE THREAD

**Issue by nrenzoni** [fsharplang-ru/pulsar-client-dotnet#199]
# Setup

running pulsar in docker:
```docker run -it -p 6650:6650 -p 8080:8080 apachepulsar/pulsar:2.8.1  bin/pulsar standalone | tee /tmp/pulsar-docker-log```

using Pulsar.Client 2.9.3, net6.0
OS: 5.10.0-0.bpo.3-amd64 #1 SMP Debian 5.10.13-1~bpo10+1 (2021-02-11) x86_64 GNU/Linux

C# code: [gist](https://gist.github.com/nrenzoni/1d86d913b9a50ee14b4851adc5bc3011)

---

# Summary of client code:

create consumer (to create subscription), dispose consumer, producer sends one message, dispose producer, create new consumer, consume single message, ack the message ID, then dispose consumer.

# Results

after creating new consumer on "test-topic", readPosition jumps to "10:1" (i.e. it has read the single message in the backlog without explicitly receiving). (I tried with producing 100 messages, the read position jumps to the end of the message queue in this case too.)

consumer receives the message, after acking the message, nothing immediately changes on internalStats (http://localhost:8080/admin/v2/persistent/public/default/test-topic/internalStats).

after ```consumer.UnsubscribeAsync()```, "test-subscriber" is deleted from "cursors" on internalStats for some reason. This is the root cause / bug / unexpected behavior.

As a result, after reusing the "test-subscriber" in a new consumer (not in C# code), the following variables reset - ```"markDeletePosition": "10:-1" and "readPosition": "10:0"```.

When using the python client (pulsar-client) and consuming a single message, the cursor does not get deleted, and "markDeletePosition" and "readPosition" advance by 1 as expected, and the subscription cursor does not get deleted.

Using the dot-pulsar library in my environment had different issues. So perhaps the root cause is dotnet. I ran all clients on both dotnet 5 and dotnet 6 and on Windows 10 (but didn't verify the exact behavior that the cursors got deleted).

I believe the relevant part of log is here:

```
13:46:13.857 [pulsar-io-29-36] INFO  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://public/default/test-topic][test-subscriber] Successfully closed subscription [ManagedCursorImpl{ledger=public/default/persistent/test-topic, name=test-subscriber, ackPos=10:-1, readPos=10:1}]
13:46:13.871 [bookkeeper-ml-scheduler-OrderedScheduler-2-0] INFO  org.apache.bookkeeper.mledger.impl.MetaStoreImpl - [public/default/persistent/test-topic] Remove consumer=test-subscriber
13:46:13.879 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedLedgerImpl - [public/default/persistent/test-topic] [test-subscriber] Deleted cursor
13:46:13.880 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.pulsar.broker.service.persistent.PersistentSubscription - [persistent://public/default/test-topic][test-subscriber] Successfully deleted subscription
13:46:13.880 [bookkeeper-ml-scheduler-OrderedScheduler-0-0] INFO  org.apache.pulsar.broker.service.Consumer - Unsubscribed successfully from PersistentSubscription{topic=persistent://public/default/test-topic, name=test-subscriber}
13:46:13.883 [BookKeeperClientWorker-OrderedExecutor-11-0] INFO  org.apache.bookkeeper.mledger.impl.ManagedCursorImpl - [public/default/persistent/test-topic][test-subscriber] Deleted cursor ledger 11
```

I attached the log file, with dividers (---) to differentiate the different stages of the consumers & producer. (Scroll to the end of the file for the relavant sections): [pulsar-docker-log-1.txt](https://github.com/fsharplang-ru/pulsar-client-dotnet/files/7634584/pulsar-docker-log-1.txt)

Any feedback is appreciated!

**Comment by Lanayx** [comment]
Hi, @nrenzoni ! This is an expected outcome, since the whole purpose of UnsubscribeAsync is to delete subscription, what did you expect this method to do?

**Comment by nrenzoni** [comment]
Hi @Lanayx , thank you so so much for responding! 

You're right, that was a silly mistake by me and I should have noticed it! 

However, I removed the line ```await consumer.UnsubscribeAsync();``` and noticed that the Pulsar stats ```markDeletePosition``` is still set to ```10:0``` and ```messagesConsumedCounter``` is still set to ```0``` (i.e., the ack message was not processed by Pulsar), even though the client code receives and acks the message. But when I do the same steps using the Python client, these fields do advance as expected.

Maybe I'm overlooking something silly?

Any thoughts?

**Comment by Lanayx** [comment]
@nrenzoni can you please add `await Task.Delay(110)` after the acknowledgment and test again? The purpose of this delay is to wait for ack to be sent, since for performance reasons it's not sent immediately, but in batches.

**Comment by nrenzoni** [comment]
@Lanayx thank you for the quick response, this solved it!

Perhaps ```consumer.DisposeAsync()``` should send all outstanding (queued) ack messages to the broker? My code had this line in it, and yet the acks aren't sent.

(Also another quick solution would be ```client.NewConsumer()...AcknowledgementsGroupTime(TimeSpan.Zero)```, causing the acks to be sent immediately.)

The simple example here: [CsharpExamples/Simple.cs](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/examples/CsharpExamples/Simple.cs) also has the unexpected behavior of the ack not getting sent to the broker (and I would assume the same occurs in the equivalent F# code). Perhaps the examples code should be updated? (Although I noticed that this example [CsharpExamples/RealWorld.cs](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/e26c7bd7c4051e27b42adc94f65b0c9558e2c923/examples/CsharpExamples/RealWorld.cs#L95) does specify waiting for acks to be sent, but probably all the examples should behave correctly so that new users aren't confused by this default behavior.)

Thank you for solving this issue for me!!

**Comment by Lanayx** [comment]
I'm glad that it helped! As for examples, they actually will all work correctly, since there is `Console.ReadKey()` and the end of the program :) I was reluctant to add this to Simple example because people can think that they have to wait after each acknowledgment, which is definitely not the case (the wait should really happen only before closing the consumer)

As for sending on Dispose it's a good idea, but we need to keep the behavior exactly the same as in Java client, so if it sends acks on Close so should we, but if I recall correctly it doesn't do it.

**Comment by nrenzoni** [comment]
Ah good catch and thanks for pointing out the ```Console.ReadKey()``` behavior, I was looking just at ```Simple.cs``` and not the entry point code in ```Program.cs```. Your logic is sound regarding not wanting to confuse people with having to wait after every ack.

I did a static code overview of the Java Pulsar client, it looks like it does flush pending acks when ```consumer.closeAsync()``` is called. Here is the code flow:

`ConsumerImpl.closeAsync()` &rarr; `ConsumerImpl.closeConsumerTasks()` &rarr; `PersistentAcknowledgmentsGroupingTracker.close()` &rarr; `PersistentAcknowledgmentsGroupingTracker.flush()`.

`PersistentAcknowledgmentsGroupingTracker.flush()` flushes all pending acks and sends them to the broker.

I didn't execute the code so didn't dynamically verify it.

**Comment by Lanayx** [comment]
Thanks for the investigation, you are right :) So I'll keep the issue open to close after updating the behavior to conform Java's

**Comment by nrenzoni** [comment]
Ok sounds good, thanks for quick follow-up / responses!

**Comment by Lanayx** [comment]
@nrenzoni This should be fixed in 2.9.4, can you please check

**Comment by nrenzoni** [comment]
@Lanayx I ran the consumer dispose (```await using var consumer1```) on a simple test case, it appears to flush outstanding acks as expected. I can't comment on the actual F# code since I'm not versed in F# (and the syntax seems rather complicated compared to C# or other coding languages!).

 Good job on this fix and on the timeliness!

**Comment by Lanayx** [comment]
Thanks for confirming, I'm closing the ticket.

BTW, as for F# vs C# complexity I've got a presentation you might find interesting :) https://docs.google.com/presentation/d/1PMFcU-VPkexfHG9iKO8EgBhPYkrGFg1Uy_7jZ-UuqWw/edit?usp=sharing

**Comment by nrenzoni** [comment]
Thanks @Lanayx  for the slides! :grinning:
