### ISSUE TITLE
It is not possible to use an enum in the same schema twice

### ISSUE THREAD

**Issue by ThomasHarzer** [fsharplang-ru/pulsar-client-dotnet#201]
I want to use a schema derived from a record class using the same enum twice:

```
public sealed record Article(
    int Id,
    string ArticleNumber,
    ArticleState CurrentStatus,
    ArticleState StatusBefore);

public enum ArticleState
{
    Active,
    Inactive,
}
```
When I'm going to instantiate a producer like this (Schema.JSON or Schema.AVRO doesn't matter):

```
var producer = await client
    .NewProducer(Schema.AVRO<Article>())
    .Topic("some-topic")
    .CreateAsync();
```

it will produce an exception like this:

`Avro.AvroException: Duplicate schema name ArticleState`

Obviously, the enum in the first place is redefined and not reused in the second place. Is this a bug or do I miss something?

See https://stackoverflow.com/questions/67632440/avro-multiple-enum-int-the-same-type-avro-schemaparseexception-cant-redefine for a possible solution.

**Comment by Lanayx** [comment]
Hi, @thomasharzer ! Can you please create an issue in https://github.com/eaba/AvroSchemaGenerator repository as Pulsar.Client relies on it for schema generation

**Comment by Lanayx** [comment]
Closing issue as abandoned
