### ISSUE TITLE
Performance Discrepancy between pulsar-client-dotnet and DotPulsar 

### ISSUE THREAD

**Issue by adminnz** [fsharplang-ru/pulsar-client-dotnet#207]
When running a simple console App to publish messages (as byte[]) the most basic producer in DotPulsar and pulsar-client-dotnet.
Against a locally running Pulsar (in minikube), results in DotPulsar being able to produce twice as many messages per second, as this library.

```
var client = await new PulsarClientBuilder()
                .ServiceUrl("pulsar://localhost:6650")
                .BuildAsync();

var producer = await client.NewProducer()
               .Topic("mytopic")
               .ProducerName("test")
               .CreateAsync();
JsonSerializerOptions Options = new JsonSerializerOptions();
while(true)
{
    var myObject = new MyObject();
    await producer.SendAsync(JsonSerializer.SerializeToUtf8Bytes(myObject, Options));
}
```

vs DotPulsar which from what I can tell is the exact same config.
```
await using var client = PulsarClient.Builder().ServiceUrl(new Uri("pulsar://localhost:6650")).Build();
var producer = client.NewProducer().Topic("mytopic").Create();
JsonSerializerOptions Options = new JsonSerializerOptions();
while(true)
{
    var myObject = new MyObject();
    await producer.Send(JsonSerializer.SerializeToUtf8Bytes(myObject, Options));
}
```

Note: I've omitted the App.Metrics code used to measure message rates.

- Has performance between the two libraries been established (outside of my findings) ?
- Is there maybe something I'm doing wrong that results in pulsar-client-dotnet to perform so badly?

**Comment by Lanayx** [comment]
Hi! If I recall correctly dotpulsar doesn't support batching, so it probably defaults to unbatched message send. Pulsar-client-dotnet sticks to Java defaults with batching enabled with 1ms batch size, so if I expect you to be able to send around 1k messages in the mentioned configuration. So disabling batching should help, but for real highload you need to keep batching and not awaiting each send in loop, rather using continueWith or special queue for produce tasks to be awaited on a separate thread

**Comment by adminnz** [comment]
Hmm, okay, well i wasn't even able to achieve over 63 messages/second with the above code. 
Note: this is on a rather limited laptop with minikube, so might be a bad test machine.

**Comment by Lanayx** [comment]
Hmm, you are right, 1 ms is for gathering a batch and then it waits for the acknowledgement much longer. Anyway you should try the ways I described above

**Comment by Lanayx** [comment]
@adminnz Hey, any updates?

**Comment by Lanayx** [comment]
Closing as abandoned
