### ISSUE TITLE
Need ability to read events for a given key

### ISSUE THREAD

**Issue by DR9885** [fsharplang-ru/pulsar-client-dotnet#208]
In some cases I only want the events for a given key, it would be nice if pulsar client could allow reading only for this one key.

Example: (read events for key 123)
``` 
await _client.NewReader()
                .Topic($"persistent://public/default/{bucket}")
                .StartMessageId(MessageId.Earliest)
                .Keys(new[] {"123"})
                .CreateAsync();
```

**Comment by Lanayx** [comment]
Hello! If you want server-side key filtering, then it's not supported by pulsar. As for client-side filtering we are sticking to the [Java functionality ](https://pulsar.apache.org/docs/en/client-libraries-java) so adding new api's is restricted. Also you can easiliy implement client side filtering yourself when handling messages.

**Comment by DR9885** [comment]
@Lanayx if I wanted server-side key filtering, should I just open a ticket here? https://github.com/apache/pulsar

**Comment by Lanayx** [comment]
Yes, but I think such ticket must already exist, so you better try finding it and voting

**Comment by DR9885** [comment]
didnt see one, opened ticket: https://github.com/apache/pulsar/issues/15268
