### ISSUE TITLE
Not able to connect with Pulsar Webscocket

### ISSUE THREAD

**Issue by gou02rav32** [fsharplang-ru/pulsar-client-dotnet#21]
Hi I am getting exception 
16:50:55.817 [pulsar-io-49-6] WARN  org.apache.pulsar.common.api.PulsarHandler - [[id: 0xbb072290, L:/192.168.1.52:6650 - R:/192.168.1.52:52543]] Forcing connection to close after keep-alive timeout. 
whenever I am attempting to connect the Pulsar web socket I am getting above exception.

**Comment by Lanayx** [comment]
Project is in early development, please read readme
