### ISSUE TITLE
KeyShared fails to partition correctly when SequenceId is not set

### ISSUE THREAD

**Issue by DR9885** [fsharplang-ru/pulsar-client-dotnet#210]
Is it expected behavior, that KeyShared fails to partition correctly when SequenceId is not set?

**Comment by Lanayx** [comment]
Hi, no this is not expected. [Here are](https://github.com/fsprojects/pulsar-client-dotnet/blob/develop/tests/IntegrationTests/Keys.fs) the key-related integration tests, feel free to add a PR with a failing test.

**Comment by DR9885** [comment]
Is it ok if I just give a C# Example?

**Comment by Lanayx** [comment]
C# example won't run integration test after you submit it :(

**Comment by DR9885** [comment]
nvm, It was bad data in a test.
