### ISSUE TITLE
PulsarClient.CloseAsync seems not to work correctly

### ISSUE THREAD

**Issue by SonicYeager** [fsharplang-ru/pulsar-client-dotnet#222]
When using the real world example in a worker service in a .NET project i get the following warning:
![image](https://user-images.githubusercontent.com/69338558/228923253-1335e823-6c9c-4e2a-9517-ba42620f8999.png)

I just used the method in the template worker in the BackgroundWorker dotnet template. As it seems the client also still has a connection and sends/receives keepalive ticks. I think that behaviour is incorrect. 
Is there any incompatability with .NET 7?
Latest nuget is used.

**Comment by Lanayx** [comment]
Thanks for reporting, can you please check 2.12.0 version, if it works well.

**Comment by SonicYeager** [comment]
Thx for answering that quickly. 
Thats now the log:
![image](https://user-images.githubusercontent.com/69338558/228936469-69b376db-3b27-4bd1-9125-12d87bc417de.png)

Improvement, yet i expect  no failures...

**Comment by Lanayx** [comment]
I've just updated RealWorldExample so there is no error log anymore, as well as published 2.12.2 with no keepalive ticks, you are welcome to test

**Comment by SonicYeager** [comment]
Will do. I'll give you feedback as soon as I have it.

**Comment by SonicYeager** [comment]
The log:
![image](https://user-images.githubusercontent.com/69338558/229036559-4c7800bd-7556-4b8b-96f7-31e99fbfc3f2.png)

In the further log i dont find any closed/stopped client. In 1.12.0 there was an log entry with "Client has Stopped" or something alike. Thats still missing. Therefore in assume the client is still not correctly closed/disposed?
When i look at the git history it looks as if the latest additions with socket disposal in the ClientCnx and ConnectionPool might cause this..., As i am not a F# Dev i have trouble understanding what exactly causes this. I assume based on what i have observed and i think i understand from the implementations.

The rest seems to operate correctly so far while using the updated example.

**Comment by Lanayx** [comment]
<img width="323" alt="image" src="https://user-images.githubusercontent.com/3329606/229045513-016a2f68-8f2d-4ae7-860e-c9be8603e322.png">
I've just checked realworld example and I do see "Pulsar client stopped" message. It is not the last one, since it's not waiting for everything else to dispose. Warning are also expected, since dispose actually disposes sockets and this leads to exceptions.

**Comment by SonicYeager** [comment]
Thank you for checking. I can confirm that. Apologies, that i have overlooked it.

**Comment by SonicYeager** [comment]
To make sure i understand correctly and do not misinterpret the logs:

- The warning comes as the socket gets disposed while a process is still using it or because at another place it is tried to be disposed?
- The logs still count up the "id" for the ClientCnx, does this happen apart from the client instances?

**Comment by SonicYeager** [comment]
I consider the issue closed as the actual matter has been resolved. 
Thank you for the quick replies and actions. 👍🏻 ✌🏻

**Comment by Lanayx** [comment]
@SonicYeager for your questions:
- Client logs warning for any time the connection is stopped, was it dropped intentionally or not, that's for consistency
- Yes, client is built using "actor model" where PularClient, Consumer, Producer, ClientCnx etc are independent actors and are stopped independently
- There are usually two ClientCnx instances - one connects to broker, another one can only connect to proxy, hense it's "brokerless" in code
