### ISSUE TITLE
Pulsar.Client.Api.TimeoutException: clientCnx(1, LogicalAddres Unspecified/localhost:6650)

### ISSUE THREAD

**Issue by leejh6182** [fsharplang-ru/pulsar-client-dotnet#223]
Hello
I am using pulsar-client-dotnet in my application.
To send heartbeat of application, create producer and send message in every 2 seconds.
Below is the code for creating client and creating producer to send heartbeat.
For application specific feature, i made all async method to work as synchronous.

    string connUrl = $"pulsar://{_serviceUrl}:{_brokerPort}";
    var _client = new PulsarClientBuilder()
                               .ServiceUrl(connUrl)
                               .BuildAsync().Result;

    public void Send(string topic, string message) 
    {
        var producer = _client.NewProducer()
                                       .Topic($"persistent://{_tenant}/{_namespc}/{topic}")
                                       .CreateAsync().Result;
        var msg = producer.NewMessage(Encoding.UTF8.GetBytes(message.GetDataAsString()), "C#", messageProperties);

        try
        {
            var task = producer.SendAsync(msg).Result;
            if (task == null)
            {
                throw new Exception($"Failed to send message {message}");
            }
        }
        catch (Exception ex)
        {
             throw;
        }
    }

At the beginning, it sends heartbeat successfully. But after few minute, it fails to send message with below error message

![image](https://user-images.githubusercontent.com/17683133/230863099-375d0b1c-1635-4706-8fb9-71344dbfd006.png)

Any clue for root cause of solution? 

Thank you!

**Comment by Lanayx** [comment]
Hi! I haven't tried to reproduce it, but the approach doesn't seem to be correct - producer shouldn't be created on each message send, rather once for the whole application lifetime. So, if you **do** need to create producer on each message (for example you have millions of topics in cluster even if it's not the best idea) then you should dispose your producer in the end of the method. From the exception above it seems like pulsar cluster can't handle that many open producers

**Comment by leejh6182** [comment]
Hello @Lanayx
Thank you for your guide.
Actually i have tried below 2 options.
1. Use one producer for whole message
2. Use new producer for every message and dispose every time

Both seem to have problem. 
When sending message in every 2 seconds, it fails at certain time. 
Timeout error or fail to send error are generated.

**Comment by Lanayx** [comment]
Can you please create a console app that will start failing after running few minutes? Most probably it will be a loop with 2 sec delay. Once created you can attach it here to the issue as a zip file

**Comment by Lanayx** [comment]
Closing as abandoned
