### ISSUE TITLE
Producer hangs when using BatchBuilder.KeyBased

### ISSUE THREAD

**Issue by adrianotr** [fsharplang-ru/pulsar-client-dotnet#228]
When using the KEY_BASED BatchBuilder it is impossible to send messages. The producer hangs forever and nothing happens.

Sample code:
```csharp
var client = await new PulsarClientBuilder()
    .ServiceUrl("pulsar://localhost:6650")
    .BuildAsync();

await using var producer = await client.NewProducer(Schema.STRING())
    .Topic("some-topic")
    .EnableBatching(true)
    .BatchBuilder(BatchBuilder.KeyBased)
    .CreateAsync();

// this hangs when using BatchBuilder.KeyBased
await producer.SendAsync("Oh no!");
```

I've tested this code against pulsar:2.11.0 and pulsar:3.0.0.
The Pulsar.Client version is 2.12.6.

**Comment by adrianotr** [comment]
I've just noticed that, if we specify the message key, then this issue does not happen:

```csharp
var message = producer.NewMessage(data, someKey);
await producer.SendAsync(message);
```

Is that the intended behavior?

**Comment by Lanayx** [comment]
KeyBased batch builder is intended to be used with keyed messages, so sending a message without key is not expected. However even though it's not expected, it shouldn't hang, so I'll have a look

**Comment by adrianotr** [comment]
According to the [Pulsar Docs](https://pulsar.apache.org/docs/3.0.x/concepts-messaging/#batching-for-key-shared-subscriptions), messages without a key are packed in one batch.

That also brings me one question: What should happen when messages have an OrderingKey?

**Comment by adrianotr** [comment]
To answer my own question: 

> What should happen when messages have an OrderingKey?

It will use the ordering key as the batch key, when the ordering key is specified, as seen in the [source code](https://github.com/fsprojects/pulsar-client-dotnet/blob/develop/src/Pulsar.Client/Internal/BatchMessageContainer.fs#L150).

**Comment by Lanayx** [comment]
I've pushed a fix for empty key case, will publish a nuget once CI will pass. However what I've found that the docs from pulsar site you linked don't correspond to the code - NON_KEY value is never sent (such thing doesn't exist in the codebase) so I just used empty string as well.
