### ISSUE TITLE
Add support for setting 'ReplicateSubscriptionState' while creating a consumer

### ISSUE THREAD

**Issue by Akash98Sky** [fsharplang-ru/pulsar-client-dotnet#229]
Reference: https://github.com/apache/pulsar/pull/4299
API: https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/ConsumerBuilder.java#L397-L401

**Comment by Lanayx** [comment]
Completed in 3.4.0 (https://github.com/fsprojects/pulsar-client-dotnet/pull/261)
