### ISSUE TITLE
EventTime on reconsumed message is always null

### ISSUE THREAD

**Issue by RufusK** [fsharplang-ru/pulsar-client-dotnet#234]
Hi, for our understanding the EventTime in Pulsar.Client.Common.Message is when the initial message was published. This should not change when the message gets send to the Retry Letter Queue. (As the PublishTime does)
When we set the EventTime on the MessageBuilder, the consumed message includes the correct EventTime, but when we use ReconsumeLaterAsync, the next time we consume the message the EventTime is always null. There is also no option to set any of the metadata directly when using ReconsumeLaterAsync.

Would it be possible to pass the EventTime from the original message to the message that is put on the Retry Letter Queue?

Btw, thanks for the awesome library that makes our lives a lot easier everyday.

Cheers, Klaus

Pulsar-Client-Dotnet Version 2.13.1
We use the Library with C# .Net 6/7

**Comment by Lanayx** [comment]
Hi, Rufus! I agree, that EventTime should be persisted, although it is missing in the original Java client as well. Please check 2.13.2 version, it should fix the issue for you.

**Comment by RufusK** [comment]
You are way ahead of the java client :) Thanks a lot for the quick response, you once again saved our lives. I tested it, everything works as expected.
