### ISSUE TITLE
Add Transaction supported on 2.9+

### ISSUE THREAD

**Issue by Genuineh** [fsharplang-ru/pulsar-client-dotnet#237]
Thanks for your work

I can't use transaction on plusar cluster version 2.9+. like 2.9, 2.10, 3.x and so on  but java client is ok

I got error when start transaction by producer like
 "Unhandled exception. Pulsar.Client.Api.CoordinatorNotFoundException: Transaction coordinator with id 1 not found!
   at <StartupCode$Pulsar-Client>.$TransactionMetaStoreHandler.-ctor@148-163.MoveNext()
   at <StartupCode$Pulsar-Client>.$TransactionBuilder.BuildAsync@34.MoveNext()"

Please join the plan to support the new version on transaction

**Comment by Lanayx** [comment]
@Genuineh can you please find some Pulsar reference to what changed in transactions between 2.8 and 2.9? Maybe github issue or blogpost. Ideally even the PR with changes

**Comment by Genuineh** [comment]
I can give it a try but need some time

**Comment by Genuineh** [comment]
I found a change in the agreement that may happen on [#13135](https://github.com/apache/pulsar/pull/13135) Commit from [2.9.2 release note](https://pulsar.apache.org/release-notes/versioned/pulsar-2.9.2/). Can you take a look? I'm not familiar with F# myself, so I can't apply it quickly.

**Comment by Lanayx** [comment]
Thanks, this looks relevant, I'll dig there when I have more time

**Comment by Lanayx** [comment]
@Genuineh I've done some testing and found that it integration tests are broken between 2.8.1(Sep 7, 2021) and 2.9.0 (Nov 25, 2021), while the commit above was merged Dec 14, 2021, so it seems that it was not the case

**Comment by Genuineh** [comment]
@Lanayx I couldn't find any content related to this exception in the transaction-related commits and discussions from 2.8.1-2.9.0, and it seems that their approach in the 2.9.2 update is to prevent users from being aware of this exception on their end and they have implemented an internal retry mechanism. It is possible that previous transaction-related changes may have triggered this exception logic, but will retrying be able to resolve the problem? I'm not very clear about the internal implementation mechanism and code, so I'm not sure what caused it. However, if such an issue occurs, is it possible that there have been relevant notifications in the official communication group? The official issue resolution speed is quite slow, so I'm wondering if there are any faster channels on your end to confirm the cause of this problem and the related solution?

**Comment by Lanayx** [comment]
The retry is already implemented in Pulsar.Client, you can see it in logs, exception get raised after several tries  It looks like something changed about transactions implementation on broker side. I don't have any channels except official, so only digging into the Java code can help.

**Comment by Lanayx** [comment]
@Genuineh I've spent some time today investigating the issue and could not make transaction coordinator work even without any client library. 
I've followed this guide https://pulsar.apache.org/docs/3.1.x/txn-use/ and then tried to get coordinator stats
https://pulsar.apache.org/docs/3.1.x/admin-api-transactions/#get-coordinator-stats
and it returned the same error `Transaction coordinator not found! coordinator id : 1`

So I expect that once you'll be able to make it work from admin side the library will work for you as well.

**Comment by Lanayx** [comment]
Good news, I've investigated git history and found some relevant commits
https://github.com/apache/pulsar/pull/12301
https://github.com/apache/pulsar/pull/12219
https://github.com/apache/pulsar/pull/11357

**Comment by Genuineh** [comment]
I have also tried quite a few approaches to adjust the server settings, but they didn't have any effect. However, it's really great to see this, looking forward to what comes next.

**Comment by Lanayx** [comment]
Hey, I've just published https://www.nuget.org/packages/Pulsar.Client/2.14.0 , it should resolve the issue for you. It indeed appeared that protocol was changed in 2.9 and that https://github.com/apache/pulsar/pull/12301 was the commit that fixed it for Java client, so I applied changes from there and it worked. Tested on 2.9.0 and 2.11.2

**Comment by Genuineh** [comment]
@Lanayx Thanks for your working, it worked on version 3.x normally too
