### ISSUE TITLE
Dead lock when consumer enable retry and call "isConnected" multiple times

### ISSUE THREAD

**Issue by Genuineh** [fsharplang-ru/pulsar-client-dotnet#247]
Hello, thanks for your contribution，i found dead lock when i enable the retry option and call "isConnected" multiple times.
And I have found the code that may potentially cause a deadlock.
```F#
member this.IsConnected =
    (postAndAsyncReply mb IsConnected).Result
```
Async method used in sync method like ".Result" maybe cause a dead lock.
I think we can change all method to async or check async method‘s execution status in loop to instead of ".Result".

**Comment by Lanayx** [comment]
I've made updates in 3.2.0, please check

**Comment by Genuineh** [comment]
The basic test is fine, but more usage scenarios are needed to verify that deadlock has been eliminated
