### ISSUE TITLE
Support InitialSubscritionName for DLQ

### ISSUE THREAD

**Issue by adrianotr** [fsharplang-ru/pulsar-client-dotnet#249]
Hello!

Currently the pulsar-client-dotnet api does not expose a way to create a initial subscription for dead-letter topics.
However, topics without any subscriptions do not retain messages.
Pulsar [supports this already](https://github.com/apache/pulsar/issues/13408), and it seems we already have the parameter mapped in the [Protobuf](https://github.com/fsprojects/pulsar-client-dotnet/blob/07df121f3baa0fc787243a35ca21e36a6d6c2159/src/Pulsar.Client.Proto/PulsarApi.proto#L505).

Can we add the `InitialSubscriptionName` attribute to the [DeadLetterPolicy](https://github.com/fsprojects/pulsar-client-dotnet/blob/07df121f3baa0fc787243a35ca21e36a6d6c2159/src/Pulsar.Client/Api/DeadLetters.fs) and send that to Pulsar during the Consumer subscription using the existing Protobuf attribute?

**Comment by adrianotr** [comment]
I've created [this PR](https://github.com/fsprojects/pulsar-client-dotnet/pull/250/files) just to give you an idea of the changes needed.

**Comment by Lanayx** [comment]
Hi, @adrianotr ! Thank you for the contribution, you can continue working on PR and I'll merge it once ready. Please, don't forget to add integration test for this new feature as well.

**Comment by adrianotr** [comment]
Hi! I've pushed a new PR with an integration test: https://github.com/fsprojects/pulsar-client-dotnet/pull/273

**Comment by Lanayx** [comment]
Published https://www.nuget.org/packages/Pulsar.Client/3.6.0, can you please verify?

**Comment by adrianotr** [comment]
Hi @Lanayx! I've tested the new feature and it works as expected. Thanks for your support!
