### ISSUE TITLE
Authentication token by suplier

### ISSUE THREAD

**Issue by gavrilyuc** [fsharplang-ru/pulsar-client-dotnet#252]
How can I use this variant in dotnet?
https://github.com/apache/pulsar/blob/master/pulsar-client-api/src/main/java/org/apache/pulsar/client/api/AuthenticationFactory.java#L54-L56

I don't find any information for c# in [docs](https://pulsar.apache.org/docs/3.1.x/security-jwt/#configure-jwt-authentication-in-pulsar-clients)

But it has in Go and Java.

**Comment by Lanayx** [comment]
Thanks for asking! The logic was already there, but not exposed, so I've exposed it in 3.3.0
