### ISSUE TITLE
What's the release strategy for the v2.x

### ISSUE THREAD

**Issue by RobertIndie** [fsharplang-ru/pulsar-client-dotnet#267]
Starting from version 3.0.0, only .NET 8.0 and above are supported. However, many applications are not compatible with .NET 8.0 and still rely on version 2.X.

What is our release strategy for version 2.X? Is it still being actively maintained? Will there be new features added to version 2.X? When will it reach the end of support?

Thanks.

**Comment by Lanayx** [comment]
Release strategy for 2.x is "on demand", so whenever someone wants a feature or a bug fix, they create a PR to 2.x and I review and release a new package after merge. The release strategy for 3.x is the same, but PR to develop branch. The only difference that sometimes I do performance optimizations and refactoring for 3.x and not for 2.x. I don't currently add any new features to any branch for free as mentioned in the [README](https://github.com/fsprojects/pulsar-client-dotnet/blob/develop/README.md#maintaners), only help supporting existing code and reviewing PRs.

**Comment by RobertIndie** [comment]
Thanks for your explanation!
