### ISSUE TITLE
Add CI build + unit tests check

### ISSUE THREAD

**Issue by Rizzen** [fsharplang-ru/pulsar-client-dotnet#4]
It might be AppVeyor, Travis or Azure Pipelines.

**Comment by Rizzen** [comment]
Mac and Linux build made in https://github.com/fsharplang-ru/pulsar-client-dotnet/pull/8 Windows build is on the way.

**Comment by Lanayx** [comment]
@Rizzen can you please add build widget to the readme page as well (example https://github.com/giraffe-fsharp/Giraffe)

**Comment by Lanayx** [comment]
Closing as half-done
