### ISSUE TITLE
Add support for tls authentication

### ISSUE THREAD

**Issue by Lanayx** [fsharplang-ru/pulsar-client-dotnet#81]
[Implementation reference](https://github.com/apache/pulsar/blob/master/pulsar-client/src/main/java/org/apache/pulsar/client/impl/auth/AuthenticationTls.java)
[Documentation reference](https://pulsar.apache.org/docs/en/security-tls-authentication/)

**Comment by MikeDotNetty** [comment]
This enhancement would be much appreciated. Any insight as to if/when this might be implemented?

**Comment by Lanayx** [comment]
@MikeDotNetty you can track team activity [here ](https://github.com/fsharplang-ru/pulsar-client-dotnet/projects/1). This issue is not in progress right now, so we'll start it after finishing current ones. That being said, you are very welcome to work on this and we'll help you with that.

**Comment by Lanayx** [comment]
@MikeDotNetty tls auth was added in 0.18.0 release

**Comment by MikeDotNetty** [comment]
Was this fully implemented?  Reason I ask is the referenced documentation from the official pulsar client allows for both a cert ".pem" file and a key ".pem" file, but this implementation only accepts a cert file.  Am I missing something?

**Comment by Lanayx** [comment]
You can check the example [here](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/examples/CsharpExamples/TlsAuthentication.cs), the key should be provided together with cert in pfx container, will this work for you? 
[Reference question on SO1](https://stackoverflow.com/questions/6307886/how-to-create-pfx-file-from-certificate-and-private-key) 
[Reference question on SO2](https://stackoverflow.com/questions/808669/convert-a-cert-pem-certificate-to-a-pfx-certificate)

**Comment by MikeDotNetty** [comment]
@Lanayx Thanks, I thought I might have to create the pfx container from the pem files, but couldn't find any good links, much appreciated!

**Comment by MikeDotNetty** [comment]
@Lanayx, so let me start by saying, it's very possible the PFX i generated via openssl or the CA.pem file I am using are corrupt.  However, when I implemented code similar to the TlsAuthentication example (modifying it for my individual use case) and I run it in visual studio, it appears to fail inside the pulsar client, however the pulsar client is not providing any usable errors.  The only output it get is the process "has exited with code 0".  Specifically this "output" is generated on the "ProducerBuilder" line of code.  Any insight would be appreciated.  Thanks!

**Comment by Lanayx** [comment]
@MikeDotNetty So here are the steps I can suggest you to debug the issue:
1) Set logging level to debug and inspect logs (you can attach logs file here for me)
2) Ensure that your code works with some other cluster (local insecure or https://kafkaesque.io/ free trial). If it does work, but you cluster with tls auth doesn't, check if java/python client works with it

**Comment by Lanayx** [comment]
If you are using .net 4.6.*, then we've just published a new version for tls, appeared that additional configuration is required for the old .net version.

**Comment by MikeDotNetty** [comment]
@Lanayx Thanks again for all your help with this.  Here are the details of what I have going on:

I have set up two .net console applications to see if I can get this to work.
- A **.NET Core** (3.1) console application
- A **.NET Framework** (4.6.1) console application.   

The code is nearly identical for both these projects; with the one difference of the 4.6.1 code having the ".TlsProtocols(SslProtocols.Tls12 | SslProtocols.Tls11)" config setting and the 3.1 code not having this.  I have attached the code (modified to not expose actual endpoints, topic and subscription information), the debug output and the error each approach generates (message and stacktrace).  Please let me know if you are able to make heads or tails of this.

<-ATTACHMENTS REMOVED->

**Comment by Lanayx** [comment]
@MikeDotNetty unfortunately, those are not the logs I'm looking for, can you please setup proper logging as shown [here](https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/examples/CsharpExamples/Program.cs#L12-L18) with logging set to debug

**Comment by MikeDotNetty** [comment]
@Lanayx Thanks for that bit of insight.  Originally I tried to do that but "addConsole" keep throwing an error, apparently it's not in "Microsoft.Extensions.Logging" (as visual studio suggested), but rather it's own "Microsoft.Extensions.Logging.Console".  Either way, I have the logging information now, and  I think with this information I can do a deeper dive on my side.  As now I can see that this is what's going on...
warn: PulsarLogger[0]
      RemoteCertificateChainErrors + RemoteCertificateNameMismatch

fail: PulsarLogger[0]
      clientCnx(2, LogicalAddress Unspecified/SOMEDOMAIN:6651) CommandError Error: AuthorizationError. Message: Client is not authorized to Produce
fail: PulsarLogger[0]
      producer(1, , -1) Failed to create

**Comment by MikeDotNetty** [comment]
@Lanayx Just wanted to follow up. Now that I was able to see the log, I was able to identify that the issue was internal to the endpoint I was reaching out to.  Thank you very much for your quick responses to my questions and enabling the TLS Authentication, I can say with 100% certainty that it works great!  Thanks again!

**Comment by Lanayx** [comment]
Great news!
