### ISSUE TITLE
Build fails due to missing Paket

### ISSUE THREAD

**Issue by auduchinok** [fsharplang-ru/pulsar-client-dotnet#99]
Build instructions don't suggest installing Paket and build fails if it's not available:
```
Eugene.Auduchinok@UNIT-1032 MINGW64 /c/Developer/solutins/pulsar-client-dotnet (develop)
$ dotnet build
Microsoft (R) Build Engine version 16.6.0+5ff7b0c9e for .NET Core
...
Build FAILED.
...
C:\Developer\solutins\pulsar-client-dotnet\.paket\Paket.Restore.targets(171,5):
  error MSB3073: The command ""paket" restore" exited with code 9009.
    [C:\Developer\solutins\pulsar-client-dotnet\examples\CsharpExamples\CsharpExamples.csproj]
...
```

Installing Paket as a global tool helps.

**Comment by RahimovIR** [comment]
Сan show the result of the command `paket restore`?

**Comment by auduchinok** [comment]
OK, I've uninstalled the tool and cleaned everything it created previously:
```
dotnet tool uninstall --global Paket
git clean -dfx
```
<img width="1709" alt="Screenshot 2020-06-04 at 21 31 23" src="https://user-images.githubusercontent.com/3923587/83797231-fc8d6f00-a6aa-11ea-92cc-98f6cc07cccb.png">
<img width="840" alt="Screenshot 2020-06-04 at 21 31 53" src="https://user-images.githubusercontent.com/3923587/83797235-0020f600-a6ab-11ea-82a9-4ca78c20f785.png">

**Comment by Lanayx** [comment]
@auduchinok do you think mentioning it in readme in the root is not enough? https://github.com/fsharplang-ru/pulsar-client-dotnet/blob/develop/README.md#common-steps-before-building

**Comment by auduchinok** [comment]
Ah, sorry, I've somehow didn't notice it and skipped right to the build part. 🙂

I think it'd be great to be able to use `dotnet tool restore` for that step and to specify needed tools in a manifest file, as described [here](https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#install-a-local-tool) and [here](https://fsprojects.github.io/Paket/get-started.html#NET-Core-preferred). I've actually tried using that command after clone before looking at what's going wrong.

**Comment by Lanayx** [comment]
Converted to local tool. @auduchinok thank you for reporting
